library(gridExtra)
library(ggplot2)
source("R/helper.R")
dir = "graphics/"
theme_set(theme_bw())
mypalette()

###########################################################
## Read data generated by lv_diagnostic.R
###########################################################
x = readRDS(file="data/lv_lhs.RData")
sim_mc = readRDS(file="data/lv_mc.RData")
sim_lna = readRDS(file="data/lv_lna.RData")
d_ms_sub = readRDS(file="data/lv_ms.RData")

###########################################################
## Mark points with large values
###########################################################
dd = data.frame(x1 = x[,1], x2 = x[,2], z=(sim_mc[,3]- sim_lna[,3])^2/sim_lna[,3])
dd$Extreme = abs(dd$z) > 5 | is.na(dd$z)

g1 = ggplot(dd, aes(x1, x2)) + 
  geom_point(aes(colour=Extreme, shape=Extreme), size=2) + 
  scale_x_log10(limits=c(1e-6, 1), 
                breaks=c(10^(-6:0)), 
                labels=c(expression(10^{-6}), "", expression(10^{-4}), "", expression(10^{-2}), "", expression(10^{0}))) + 
  scale_y_log10(limits=c(1e-6, 1), 
                breaks=c(10^(-6:0)), 
                labels=c(expression(10^{-6}), "", expression(10^{-4}), "", expression(10^{-2}), "", expression(10^{0}))) +  
  xlab(expression(c[1])) + ylab(expression(c[2])) + 
  guides(colour=FALSE, shape=FALSE) + 
  annotation_logticks() + 
  scale_color_manual(values=c(2, 4)) +
  annotate("text", 10^{-6}, 10^0, label="(a)", size=4, hjust=-0.5)
#g1
g1


###########################################################
## Example simulations
###########################################################
dd_text = data.frame(Time=0, value = 100, variable="Prey", label="(b)")
g2 = ggplot(d_ms_sub) + 
  geom_step(aes(Time, value, group=sim_no), alpha=0.15) + 
  xlab("Time") + 
  ylab("Population") + 
  facet_grid(variable~., scales="free_y") + 
  geom_text(data=dd_text, aes(Time, value, label=label), size=4, hjust=-0.5)
#g2


g3 = ggplot(d_ms_sub) + 
  geom_step(aes(Time, value, group=sim_no), alpha=0.15) + 
  xlab("Time") + 
  ylab("Population") + 
  facet_grid(variable~.) 
g3


###########################################################
## Save graph
###########################################################

fname = "graphics/figure3a.jpg"
jpeg(fname, width=4*resol, height=4*resol, res=resol)
print(g1)
dev.off()


fname = "graphics/figure3b.jpg"
jpeg(fname, width=4*resol, height=4*resol, res=resol)
print(g3)
dev.off()





