library("gridExtra")
library("ggplot2")
source("R/helper.R")
dir = "graphics/"
theme_set(theme_bw())
mypalette()

###########################################################
## Read data generated by lv_diagnostic.R
###########################################################
x = readRDS(file="data/lv_lhs.RData")
maxtime = 10

if(maxtime ==10) {
  mc = readRDS(file="data/lv_mc_10.RData")
  lna = readRDS(file="data/lv_lna_10.RData")
  probs = readRDS(file="data/lv_extinction_t10.RData")
}else if(maxtime == 30) {
  mc = readRDS(file="data/lv_mc_30.RData")
  lna = readRDS(file="data/lv_lna_30.RData")
  probs = readRDS(file="data/lv_extinction_t30.RData")
} else if(maxtime == 100) {
  mc = readRDS(file="data/lv_mc_100.RData")  
  lna = readRDS(file="data/lv_lna_100.RData")
  probs = readRDS(file="data/lv_extinction_t100.RData")
}

d_ms_sub = readRDS(file="data/lv_ms.RData")

###########################################################
## Mark points with large values
###########################################################

dd = data.frame(x1 = x[,1], x2 = x[,2], z=(mc[,3]- lna[,3])/lna[,6])
dd$Extreme = abs(dd$z) > 5 | is.na(dd$z)
dd$Extreme = mc[,2] < -1 | mc[,3] < -1| mc[,4] < -1| mc[,6] < -1
#dd$Extreme[lna[,2] < -1 | lna[,3] < -1| lna[,4] < -1| lna[,6] < -1] = 2
#dd$Extreme[!dd$Extreme] = (abs(dd$z[!dd$Extreme]) > 5)*3
dd$Extreme  = factor(dd$Extreme)
dd$prob1 = probs[,1]/1000
dd$prob2 = probs[,2]/1000
#dd = dd[-c(44, 79),]
table(dd$Extreme)

g1 = ggplot(dd, aes(x1, x2))  + 
  scale_x_log10(limits=c(1e-6, 1), 
                breaks=c(10^(-6:0)), 
                labels=c(expression(10^{-6}), "", expression(10^{-4}), "", expression(10^{-2}), "", expression(10^{0}))) + 
  scale_y_log10(limits=c(1e-6, 1), 
                breaks=c(10^(-6:0)), 
                labels=c(expression(10^{-6}), "", expression(10^{-4}), "", expression(10^{-2}), "", expression(10^{0}))) +  
  xlab(expression(c[1])) + ylab(expression(c[2])) + 
  guides(colour=FALSE, shape=FALSE) + 
  annotation_logticks() + 
  scale_color_manual(values=c(2, 4)) +
  annotate("text", 10^{-6}, 10^0, label="(a)", size=4, hjust=-0.5) + 
  theme(legend.position = "top", legend.direction = "horizontal") + 
  scale_size(guide = guide_legend(title = "Extinction")) + 
  theme(legend.text = element_text(size = 8), 
        legend.title = element_text(size = 9))
g1


fname = paste0("graphics/figure3a_prey_t", maxtime, ".jpg")
jpeg(fname, width=4*resol, height=4*resol, res=resol)
print(g1 +  geom_point(aes(colour=Extreme, size=prob1)))
dev.off()

fname = paste0("graphics/figure3a_pred_t", maxtime, ".jpg")
jpeg(fname, width=4*resol, height=4*resol, res=resol)
print(g1 +  geom_point(aes(colour=Extreme, size=prob2)))
dev.off()

###########################################################
## Example simulations
###########################################################
dd_text = data.frame(Time=0, value = 100, variable="Prey", label="(b)")
g2 = ggplot(d_ms_sub) + 
  geom_step(aes(Time, value, group=sim_no), alpha=0.15) + 
  xlab("Time") + 
  ylab("Population") + 
  facet_grid(variable~., scales="free_y") + 
  geom_text(data=dd_text, aes(Time, value, label=label), size=4, hjust=-0.5)
#g2


g3 = ggplot(d_ms_sub) + 
  geom_step(aes(Time, value, group=sim_no), alpha=0.15) + 
  xlab("Time") + 
  ylab("Population") + 
  facet_grid(variable~.) 
g3


###########################################################
## Save graph
###########################################################

fname = "graphics/figure3a.jpg"
jpeg(fname, width=4*resol, height=4*resol, res=resol)
print(g1a)
dev.off()


fname = "graphics/figure3b.jpg"
jpeg(fname, width=4*resol, height=4*resol, res=resol)
print(g3)
dev.off()





